config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms
  get 'dashboard/index', to: 'dashboard#index'
  get 'dashboard/new', to: 'dashboard#new'
  get 'dashboard/create', to: 'dashboard#create'
  get 'dashboard/edit', to: 'dashboard#edit'
  get 'dashboard/update', to: 'dashboard#index'
  get 'dashboard/destroy', to: 'dashboard#destroy'
  get 'dashboard/chats', to: 'dashboard#chats'

  
  namespace :admin do
    resources :links, only: [:new, :create, :index, :show]
    resources :events, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :messages, only: [:index, :show, :destroy]
    resources :chats, only: [:index, :show, :new, :create]
    resources :chatrooms, only: [:index, :show, :new, :update, :edit, :destroy]
    resources :teachers do
      collection do
        get '/search', to: 'teachers#search'
      end
    end
    resources :parents, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      collection do
        get '/search', to: 'parents#search'
      end
    end
    resources :home do
      collection do
        get '/logged_in_users', to: 'home#logged_in_users', as: 'logged_in_users'
      end
    end
    resources :communiques, only: [:index, :show, :destroy, :new, :create, :edit, :update]
    resources :eleves, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :letters, only: [:index, :create, :new, :show]

    get '/search', to: 'eleves#search'
    resources :chatrooms do
      resource :chatroom_users
      resources :instant_messages
    end
    
  end 
  
  resources :eleves, only: [:index, :show]
  resources :teachers, only: [:index, :show]
  resources :communiques, only: [:index, :show]
  resources :home, only: [:index]
  resources :messages, only: [:show, :update, :destroy, :new, :create, :edit]
  resources :chats, only: [:index]
  resources :events, only: [:index]
  resources :links, only: [:index, :show]


  
  # resources :dashboard, only: [:index, :update, :create, :new, :edit, :destroy]
  
  # get 'home/dashboard', to: 'dashboard#index'

 
  # devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "home#index"
  resources :chatrooms do
    resource :chatroom_users
    resources :instant_messages
  end

end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
    has_many :chatroom_users
    has_many :users, through: :chatroom_users
    has_many :instant_messages
end

app/controllers/admin/chatrooms_controller.rb
class Admin::ChatroomsController < ApplicationController
    before_action :set_chatroom, only: %i[ show edit update destroy ]
  
    # GET /chatrooms or /chatrooms.json
    def index
      @chatrooms = Chatroom.all
    end
  
    # GET /chatrooms/1 or /chatrooms/1.json
    def show
    end
  
    # GET /chatrooms/new
    def new
      @chatroom = Chatroom.new
    end
  
    # GET /chatrooms/1/edit
    def edit
    end
  
    # POST /chatrooms or /chatrooms.json
    def create
      @chatroom = Chatroom.new(chatroom_params)
  
      respond_to do |format|
        if @chatroom.save
          format.html { redirect_to chatroom_url(@chatroom), notice: "Chatroom was successfully created." }
          format.json { render :show, status: :created, location: @chatroom }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @chatroom.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /chatrooms/1 or /chatrooms/1.json
    def update
      respond_to do |format|
        if @chatroom.update(chatroom_params)
          format.html { redirect_to chatroom_url(@chatroom), notice: "Chatroom was successfully updated." }
          format.json { render :show, status: :ok, location: @chatroom }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @chatroom.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /chatrooms/1 or /chatrooms/1.json
    def destroy
      @chatroom.destroy
  
      respond_to do |format|
        format.html { redirect_to chatrooms_url, notice: "Chatroom was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_chatroom
        @chatroom = Chatroom.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def chatroom_params
        params.require(:chatroom).permit(:name)
      end
  end
  

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chatroom, only: %i[ show edit update destroy ]

  # GET /chatrooms or /chatrooms.json
  def index
    @chatrooms = Chatroom.all
  end

  # GET /chatrooms/1 or /chatrooms/1.json
  def show
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms or /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.save
        format.html { redirect_to chatroom_url(@chatroom), notice: "Chatroom was successfully created." }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1 or /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to chatroom_url(@chatroom), notice: "Chatroom was successfully updated." }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1 or /chatrooms/1.json
  def destroy
    @chatroom.destroy

    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: "Chatroom was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chatroom_params
      params.require(:chatroom).permit(:name)
    end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/admin/chatrooms/_chatroom.html.erb
<div id="<%= dom_id chatroom %>" class="container">
  <div class="p-2 bg-primary text-white rounded d-flex justify-content-between my-2">
    <div class="d-flex">
      <%= link_to chatrooms_path do %>
        <i class="bi bi-arrow-left-circle text-white mx-2"></i>
      <% end %>
      <i class="bi bi-people-fill"></i>
      <%= chatroom.name %>
    </div>
    <div>
      <% if current_user.is_admin? %>
        <%= link_to edit_chatroom_path(@chatroom), class: 'text-white text-decoration-none' do%> 
          <i class="bi bi-pencil-square"></i>
        <% end %>
      <% else %>
        <%= form_with(model: chatroom, url: chatroom_chatroom_users_path(chatroom), method: :delete) do |form| %>
          <%= form.submit "Quitter", class: "btn btn-light p-0 quit-btn" %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div data-behavior="messages">
    <% @chatroom.instant_messages.order(created_at: :asc).limit(100).each do |mssge| %>
      <div class="d-flex">
        <strong class="d-flex">
          <i class="bi bi-person-circle mx-2"></i>
          <%= mssge.user.first_name%>:
        </strong>
        <div class="p-2 bg-light rounded m-3">
         <%= mssge.body %>
        </div>
      </div>
    <% end %>
  </div>

  <%= form_for [@chatroom, InstantMessage.new] do |f|%>
    <%= f.text_area :body, id: "new_message", rows: 3, autofocus: true, class: 'w-100 rounded m-3' %>
  <%end%>

</div>

app/views/admin/chatrooms/_form.html.erb
<%= form_with(model: chatroom, class: "chatroom-form") do |form| %>
  <% if chatroom.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
        <% chatroom.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/chatrooms/edit.html.erb
<h1>Modifier le groupe</h1>

<%= render "form", chatroom: @chatroom %>

<br>

<div>
  <%= link_to "Show this chatroom", @chatroom %> |
  <%= link_to "Back to chatrooms", chatrooms_path %>
</div>

app/views/admin/chatrooms/index.html.erb
<div class="container">
  <div>
   <% if current_user.is_admin? %>
     <%= link_to admin_home_index_path, class: "text-decoration-none group-dashboard" do %>
      <i class="bi bi-speedometer2"></i>
      <strong>Dashboard</strong>
     <% end %>
    <% else %>
      <%= link_to dashboard_index_path, class: "text-decoration-none my-2" do %>
        <i class="bi bi-speedometer2"></i>
        <strong>Dashboard</strong>
      <% end %>
   <% end %>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="card">
        <div class="card-header bg-primary text-white">
          Groupes rejoins
        </div>
        <div class="card-body">
          <% if user_signed_in? %>
            <ul class="list-group">
              <% current_user.chatrooms.each do |chatroom| %>
                <li class="list-group-item">
                  <i class="bi bi-people-fill"></i>
                  <%= link_to chatroom.name, chatroom, class: "text-decoration-none text-bold cursor-progress"%>
                </li>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <div class="card group">
        <div class="card-header bg-primary text-white">
          Groupes disponibles
        </div>
        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th>Name</th>
                <th colspan="3">Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @chatrooms.each do |chatroom| %>
                <tr>
                  <td><%= chatroom.name %></td>
                  <%# <td><%= link_to "Show", chatroom_path(chatroom), class: "btn btn-primary" %>
                  <td>
                    <% if current_user.is_admin?%>
                      <%= link_to "Edit", edit_admin_chatroom_path(chatroom), class: "btn btn-secondary" %>
                    <% end %>
                  </td>
                  <%# <td>
                    <%= button_to "Destroy", chatroom, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
                  
                  <td>
                    <%= form_with(model: chatroom, url: chatroom_chatroom_users_path(chatroom), method: :post) do |form| %>
                      <%= form.submit "Integrer", class: "btn btn-success" %>
                    <% end %>
                  </td>
                  <td>
                    <%= form_with(model: chatroom, url: chatroom_chatroom_users_path(chatroom), method: :delete) do |form| %>
                      <%= form.submit "Quitter", class: "btn btn-warning" %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <% if current_user.is_admin %>
          <%= link_to "+ Créer un groupe", new_admin_chatroom_path(@chatroom), class: "text-decoration-none"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/chatrooms/new.html.erb
<h1>New chatroom</h1>

<%= render "form", chatroom: @chatroom %>

<br>

<div>
  <%= link_to "Back to chatrooms", chatrooms_path %>
</div>

app/views/admin/chatrooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @chatroom %>

<%# <div>
  |
  <%= link_to "Back to chatrooms", chatrooms_path %>

  <%# <%= button_to "Destroy this chatroom", @chatroom, method: :delete %>