config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms
  get 'dashboard/index', to: 'dashboard#index'
  get 'dashboard/new', to: 'dashboard#new'
  get 'dashboard/create', to: 'dashboard#create'
  get 'dashboard/edit', to: 'dashboard#edit'
  get 'dashboard/update', to: 'dashboard#index'
  get 'dashboard/destroy', to: 'dashboard#destroy'
  get 'dashboard/chats', to: 'dashboard#chats'

  
  namespace :admin do
    resources :links, only: [:new, :create, :index, :show]
    resources :events, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :messages, only: [:index, :show, :destroy]
    resources :chats, only: [:index, :show, :new, :create]
    resources :chatrooms, only: [:index, :show, :new, :update, :edit, :destroy]
    resources :teachers do
      collection do
        get '/search', to: 'teachers#search'
      end
    end
    resources :parents, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      collection do
        get '/search', to: 'parents#search'
      end
    end
    resources :home do
      collection do
        get '/logged_in_users', to: 'home#logged_in_users', as: 'logged_in_users'
      end
    end
    resources :communiques, only: [:index, :show, :destroy, :new, :create, :edit, :update]
    resources :eleves, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :letters, only: [:index, :create, :new, :show]

    get '/search', to: 'eleves#search'
    resources :chatrooms do
      resource :chatroom_users
      resources :instant_messages
    end
    
  end 
  
  resources :eleves, only: [:index, :show]
  resources :teachers, only: [:index, :show]
  resources :communiques, only: [:index, :show]
  resources :home, only: [:index]
  resources :messages, only: [:show, :update, :destroy, :new, :create, :edit]
  resources :chats, only: [:index]
  resources :events, only: [:index]
  resources :links, only: [:index, :show]


  
  # resources :dashboard, only: [:index, :update, :create, :new, :edit, :destroy]
  
  # get 'home/dashboard', to: 'dashboard#index'

 
  # devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "home#index"
  resources :chatrooms do
    resource :chatroom_users
    resources :instant_messages
  end

end

app/models/UserChat.rb
class UserChat < ApplicationRecord
  belongs_to :user
  belongs_to :chat
end

app/models/chat.rb
class Chat < ApplicationRecord
 
  belongs_to :sender, class_name: "User"
  has_many :user_chats
  has_many :recipients, through: :user_chats, source: :user, class_name: "User"
  has_many :received_chats, class_name: "Chat", foreign_key: "sender"

end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
    has_many :chatroom_users
    has_many :users, through: :chatroom_users
    has_many :instant_messages
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/communique.rb
class Communique < ApplicationRecord
    has_one_attached :image
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/eleve.rb
class Eleve < ApplicationRecord
    # after_create_commit { broadcast_prepend_to "tweets" }
end

app/models/event.rb
class Event < ApplicationRecord
    has_one_attached :image
    has_one_attached :document
end

app/models/instant_message.rb
class InstantMessage < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/letter.rb
class Letter < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"

  has_many :received_letters, class_name: "Letter", foreign_key: "recipient_id"
  has_many :sent_letters, class_name: "Letter", foreign_key: "sender_id"

  has_one_attached :document

end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/parent.rb
class Parent < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :sent_letters, class_name: "Letter", foreign_key: "sender_id"
  has_many :received_letters, class_name: "Letter", foreign_key: "recipient_id"
  has_many :user_chats
  has_many :chats, through: :user_chats, source: :chats
  has_many :received_chats, class_name: "Chat", foreign_key: "sender"
  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :intant_messages

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true, length: { minimum: 6 }


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  def self.first_user?
    count == 1
  end


  after_create :set_first_user_as_admin

  private

  def set_first_user_as_admin
    if User.first_user?
      update(is_admin: true)
    end
  end
end

app/helpers/eleves_helper.rb
module ElevesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/shared/_communiquepopup.html.erb
<div class="popup">
  <div class="popup-content">
      <%= yield %>
  </div>
</div>

app/views/shared/_dashboardbar.html.erb
<div class="communique-popup-icon">
  <%= image_tag"logos/CBGClogo.png", class: 'my-logo-popup-icon' %>
  <h1>Tableau de bord utilisateur</h1>
  <p>Bienvenue Monsieur/Madame : <%= current_user.first_name%></p>
  <div style="background-color: #f2f2f2; padding: 10px; border-radius: 25px; display: flex; align-items: center; width: 40%; margin: 15px auto">
    <div >
      <%= image_tag "logos/user-profile-icon.png", style: " width: 30px; height: 30px; background-color: #ccc; border-radius: 50%; margin-right: 10px;" %>
    </div>
    <h4 style="margin: 0; font-size: 14px; font-weight: bold; color: #333;"><%= current_user.email %></h4>
  </div>
</div>
<div style="margin: 30px auto; width: 60%">

<div style="display:flex; justify-content: center; gap: 20px; margin: 30px">
  <%= link_to(admin_home_index_path, class: 'adminlink') do %>
     <%= image_tag("logos/home.png", class: "adminicon") %>
     <div style="align-self: center">
      <% concat "Home"%>
     </div>
  <%end%>
  <%= link_to(chatrooms_path, class: 'adminlink') do %>
     <%= image_tag("logos/chat-user-icon.png", class: "adminicon") %>
     <div style="align-self: center">
      <% concat "Chats"%>
     </div>
  <%end%>
  <%= link_to(dashboard_index_path, class: 'adminlink') do %>
     <%= image_tag("logos/message-icon.png", class: "adminicon") %>
     <div style="align-self: center">
      <% concat "Messages"%>
     </div>
  <%end%>
  <%= link_to(destroy_user_session_path, class: 'adminlink') do %>
     <%= image_tag("logos/power-off-icon.png", class: "adminicon") %>
     <div style="align-self: center">
      <% concat "Deconnexion"%>
     </div>
  <%end%>
</div>

app/views/shared/_dropdown.html.erb
<%################# Bootstrap menu ##############%>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid bg-white">
    <button class="navbar-toggler bg-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon icon-primary"></span>
    </button>
    <div class="collapse navbar-collapse p-2" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="">
          <a href="#apropos" class="nav-link" >A propos</a>
        </li>
        <li class="">
          <a class="popup-btn communiquebtnpopup nav-link">Communiqués</a>
          <%= render "shared/communiquepopup" do%>
             <div class="communique-popup-icon">
               <%= image_tag"logos/CBGClogo.png", class: 'my-logo-popup-icon' %>
             </div>
             <% if @communiques.any? %>
               <p style="color: green"><%= notice %></p>
               <h1>Communiques</h1>
               <% @communiques.each do |communique| %>
                 <div class="news">
                     <h3 style="text-decoration: underline;"><%= communique.titre %></h3> <br/>
                     <div>
                       <% if communique.image.attached? %>
                          <%= image_tag communique.image, style: "width: 80%; height: 100%; margin: 10px auto; object-fit: fit" %>
                       <% end %>
                      </div>
                      <p><%= communique.description %></p>
                     <%= link_to "Voir", communique %>
                 </div>
               <% end %>
               <% else %>
                 <p>Il n'y a pas de communique pour le moment</p>
             <% end %>
          <%end%>
        </li>
        <li class="nav-item">
          <%= link_to "Événements", events_path, :class => "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Contactez-nous", new_message_path, :class => "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Nos vidéos", links_path, :class => "nav-link" %>
        </li>
        <% if user_signed_in?%>
          <% if current_user.is_admin? %>
            <li class="nav-item">
              <%= link_to "Tableau de bord administrateur", admin_home_index_path, :class => "nav-link" %>
            </li>
            
          <% else %>
            <li class="nav-item">
              <%= link_to 'Tableau de bord utilisateur', dashboard_index_path, :class => "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, :class => "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Connexions", new_user_session_path, :class => "nav-link" %>
          </li>
          
        <%end%>
      </ul>
      <%# <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>
    </div>
  </div>
</nav>

app/views/shared/_popup.html.erb
<div class="popup">
  <div class="popup-content">
      <%= yield %>
  </div>
</div>