config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms
  get 'dashboard/index', to: 'dashboard#index'
  get 'dashboard/new', to: 'dashboard#new'
  get 'dashboard/create', to: 'dashboard#create'
  get 'dashboard/edit', to: 'dashboard#edit'
  get 'dashboard/update', to: 'dashboard#index'
  get 'dashboard/destroy', to: 'dashboard#destroy'
  get 'dashboard/chats', to: 'dashboard#chats'

  
  namespace :admin do
    resources :links, only: [:new, :create, :index, :show]
    resources :events, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :messages, only: [:index, :show, :destroy]
    resources :chats, only: [:index, :show, :new, :create]
    resources :chatrooms, only: [:index, :show, :new, :update, :edit, :destroy]
    resources :teachers do
      collection do
        get '/search', to: 'teachers#search'
      end
    end
    resources :parents, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      collection do
        get '/search', to: 'parents#search'
      end
    end
    resources :home do
      collection do
        get '/logged_in_users', to: 'home#logged_in_users', as: 'logged_in_users'
      end
    end
    resources :communiques, only: [:index, :show, :destroy, :new, :create, :edit, :update]
    resources :eleves, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :letters, only: [:index, :create, :new, :show]

    get '/search', to: 'eleves#search'
    resources :chatrooms do
      resource :chatroom_users
      resources :instant_messages
    end
    
  end 
  
  resources :eleves, only: [:index, :show]
  resources :teachers, only: [:index, :show]
  resources :communiques, only: [:index, :show]
  resources :home, only: [:index]
  resources :messages, only: [:show, :update, :destroy, :new, :create, :edit]
  resources :chats, only: [:index]
  resources :events, only: [:index]
  resources :links, only: [:index, :show]


  
  # resources :dashboard, only: [:index, :update, :create, :new, :edit, :destroy]
  
  # get 'home/dashboard', to: 'dashboard#index'

 
  # devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "home#index"
  resources :chatrooms do
    resource :chatroom_users
    resources :instant_messages
  end

end

app/models/UserChat.rb
class UserChat < ApplicationRecord
  belongs_to :user
  belongs_to :chat
end

app/models/chat.rb
class Chat < ApplicationRecord
 
  belongs_to :sender, class_name: "User"
  has_many :user_chats
  has_many :recipients, through: :user_chats, source: :user, class_name: "User"
  has_many :received_chats, class_name: "Chat", foreign_key: "sender"

end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
    has_many :chatroom_users
    has_many :users, through: :chatroom_users
    has_many :instant_messages
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/communique.rb
class Communique < ApplicationRecord
    has_one_attached :image
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/eleve.rb
class Eleve < ApplicationRecord
    # after_create_commit { broadcast_prepend_to "tweets" }
end

app/models/event.rb
class Event < ApplicationRecord
    has_one_attached :image
    has_one_attached :document
end

app/models/instant_message.rb
class InstantMessage < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/letter.rb
class Letter < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"

  has_many :received_letters, class_name: "Letter", foreign_key: "recipient_id"
  has_many :sent_letters, class_name: "Letter", foreign_key: "sender_id"

  has_one_attached :document

end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/parent.rb
class Parent < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :sent_letters, class_name: "Letter", foreign_key: "sender_id"
  has_many :received_letters, class_name: "Letter", foreign_key: "recipient_id"
  has_many :user_chats
  has_many :chats, through: :user_chats, source: :chats
  has_many :received_chats, class_name: "Chat", foreign_key: "sender"
  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :intant_messages

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true, length: { minimum: 6 }


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  def self.first_user?
    count == 1
  end


  after_create :set_first_user_as_admin

  private

  def set_first_user_as_admin
    if User.first_user?
      update(is_admin: true)
    end
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController

  before_action :authenticate_user!
  before_action :check_admin
  before_action :require_admin

  def index
    @communiques = Communique.all
    @messages = Message.all
    @events = Event.all
    @letters = Letter.all
    @chatrooms = Chatroom.all
  end

  def logged_in_users
    @logged_in_users = User.where("current_sign_in_at IS NOT NULL")
  end

  private

  def require_admin
    unless current_user && current_user.is_admin?
      flash[:error] = "You must be an admin to access this page."
      redirect_to root_path
    end
  end

  # def destroy
    # if @communique.destroy
    #   redirect_to admin_home_index_path, notice: "communique efface avec success"
    # end

    # if @message.destroy
    #   redirect_to admin_home_index_path, notice: "message efface avec success"
    # end

  # end 

  private

  def check_admin
    redirect_to root_path unless current_user.is_admin?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @communiques = Communique.all
  end
end

app/helpers/eleves_helper.rb
module ElevesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/admin/home/_navbar.html.erb
<div class="adminlogo-container">
     <%= link_to(root_path) do%> <%= image_tag"logos/CBGClogo.png", class: 'adminlogo' %> <% end %>
     <h5>Bienvenu au tableau de bord administrateur!</h5> <br/>
     <div style="background-color: #f2f2f2; padding: 10px; border-radius: 25px; margin-bottom: 10px; display: flex; align-items: center;">
        <div >
          <%= image_tag "logos/user-profile-icon.png", style: " width: 30px; height: 30px; background-color: #ccc; border-radius: 50%; margin-right: 10px;" %>
        </div>
        <h4 style="margin: 0; font-size: 14px; font-weight: bold; color: #333;"><%= current_user.email %></h4>
     </div>
</div>
<div class="adminlinks">
  <%= link_to(admin_home_index_path, class: 'adminlink') do %>
     <div style="align-self: center">
      <i class="bi bi-house-door-fill adminicon"></i>
      <span>Home</span>
      
     </div>
  <%end%>
  <%= link_to(admin_chatrooms_path, class: 'adminlink') do%>
    <div style="align-self: center">
      <i class="bi bi-chat-text-fill adminicon"></i> <span>Group chat</span>
    </div>
  <% end %>
  <%= link_to(admin_eleves_path, class: 'adminlink') do %>
     <%= image_tag("logos/eleve-icon.png", class: "adminicon") %>
     <div style="align-self: center"> 
      <% concat "Eleve"%>
     </div>
  <%end%>
  <%= link_to(admin_communiques_path, class: 'adminlink') do %>
    <%= image_tag("logos/speaker-icon.png", class: "adminicon") %>
    <div style="align-self: center">
      <% concat "Communiques" %>
    </div>
  <% end %>

  <%= link_to(admin_teachers_path, class: 'adminlink') do %>
    <%= image_tag("logos/enseignant-icon", class: "adminicon") %>
    <div style="align-self: center">
      <% concat "Enseignants" %>
    </div>
  <% end %>

  <%= link_to(admin_parents_path, class: 'adminlink') do%>
    <%= image_tag("logos/parents-icon", class: "adminicon")%>
    <div style="align-self: center">
      <% concat "Parents" %>
    </div>
  <% end %>

  <%= link_to(logged_in_users_admin_home_index_path, class: 'adminlink') do %>
    <%= image_tag("logos/logged-users-icon.png", class: "adminicon") %>
    <div style="align-self: center">
      <% concat "Utilisateurs connectés" %>
    </div>
  <% end %>
  
  <%= link_to destroy_user_session_path, method: :delete, class: 'adminlink' do %>
     <div style="align-self: center">
      <i class="bi bi-box-arrow-right adminicon"></i>
      <span>Déconnexion</span>
      
     </div>
  <% end %>
</div>

app/views/admin/home/index.html.erb
<div class="dashboard">
  <div class="main-content">
    <div class="dashboard-content">
    <div class="dashboard-home-link">
      <a href="#events" style="text-decoration: none; color: #184C72; margin: 10px">Événements</a>
      <a href="#messages" style="text-decoration: none; color: #184C72; margin: 10px;">Messages</a>
      <%= link_to "Ecrire aux parents", new_admin_letter_path, :style => "text-decoration: none; color: #184C72; margin: 10px;" %>
      <a href="#letters" style="text-decoration: none; color: #184C72; margin: 10px;">Lettres envoyées aux parents</a>
      <%= link_to "Envoyer un chat", new_admin_chat_path, :style => "text-decoration: none; color: #184C72; margin: 10px;" %>
    </div>

      <div class="plans-week">
        <div class="plan-head">
          <h4 class="section-title">Paiements</h4>
          <button class="btn-add">+ Ajouter</button>
        </div>
        <div class="message">
          Non disponible
        </div>
      </div>
      <div class="plans-week">
      <div class="plan-head">
        <h4 class="section-title" id="events">Événements</h4>
        <a href="<%= new_admin_event_path %>" class="btn-add">+ Ajouter</a>
      </div>
       <% if @events.present? %>
         <ul class="events">
           <% @events.each do |event| %>
             <li class="event">
               <div class="event-date"><%= event.date %></div>
               <div class="event-details">
                 <div class="event-title"><%= event.title %></div>
                 <div class="event-description"><%= event.description %></div>
               </div>
               <div style="margin: 15px">
                 <%= link_to "Voir", admin_event_path(event), class: "btn-show" %>
               </div>
               <div style="margin: 12px">
                 <%= button_to 'Effacer', admin_event_path(event), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-show', style: 'border: none; background-color: red' %>
               </div>
             </li>
           <% end %>
         </ul>
         <% else %>
           <div class="message">Aucun événement pour le moment.</div>
         <% end %>
      </div>

      <div class="plans-week messages">
        <div class="plan-head">
          <h4 class="section-title" id="messages">Messages</h4>
          <%# <button class="btn-delete">Tout Supprimer</button> %>
        </div>
        <div class="message-container">
          <p style="color: green"><%= notice %></p>
          <h1>Messages</h1>
          <div id="messages">
          <% if @messages.present?%>
              <% @messages.each do |message| %>
                <div class="message">
                  <div class="sender"><%= message.name %>:</div>
                  <div class="text"><%= message.message %></div>
                  <div><%= link_to "Voir", admin_message_path(message), class: "btn-show" %></div>
                  <div><%= button_to "Effacer ce message", admin_message_path(message), method: :delete, data: { confirm: "Êtes-vous sûr?" }, class: "btn-show" %></div>
                </div>
              <% end %>
           <% else %> 
              <div class="message">
                <div>Vous n'avez aucun message</div>
              </div>
           <% end %>
          </div>
        </div>
      </div>
      <div class="plans-week">
        <div class="plan-head" id="letters">
          <h1>Lettres aux parents</h1>
        </div>
        <% if @letters.present?%>
          <% @letters.each do |letter| %>
           <div class="message">
              <div class="sender">Au parent <%= letter.nom_du_parent_destinataire %></div>
              <p style="color: #3498DB"><em> ID du parent: <%= letter.recipient_id %> </em> </p>
              <div class="text"><%= letter.subject %></div>
              <div><%= link_to "Voir", admin_letter_path(letter), class: "btn-show" %></div>
            </div>
          <% end %>
        <% else %>
          <div class="message">
            <div>Vous n'avez envoyé aucune lettre pour le moment</div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/home/logged_in_users.html.erb
<div class="eleves">
  <div> 
    <h1>Les Utilisateurs </h1>
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Post nom</th>
          <th>Prénom</th>
          <th>Email</th>
          <th>Compte créé à</th>
        </tr>
      </thead>
      <tbody>
        <% @logged_in_users.each do |user| %>
          <tr>
            <td><%= user.id%></td>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>
            <td><%= user.last_sign_in_at.strftime('%b %d, %Y %I:%M %p') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/_footer.html.erb
<div class="logo-footer">
  <h2>Congolese British Grammar School</h2> <br/>
  <p>L'école propose le programme national en conformité avec le ministère de 
  l'Éducation et le programme britannique pour les écoles maternelles, primaires et secondaires. 
  L'apprentissage comprend des variétés de cours pour consolider la formation académique dans différentes disciplines soutenues 
  par l'apprentissage de la langue anglaise.</p>
</div>
<div class="contact-footer">
  <div class="contact-icon-container">
    <div> <i class="fas fa-map-marker-alt"></i></div>
    <p>Avenur Gaston Muzala, Quartier Jolie City Kazembe, Commune de Dilala, Kolwezi, Province de Lualaba, RD Congo</p>
  </div>
  <div class="contact-icon-container">
    <div><i class="fas fa-phone-volume"></i></div>
    <p>Opening hours: 8:00 AM - 4:00 Hr Pm 00243974469299 00243817301082</p>
  </div>
</div>

app/views/home/_nosvaleurs.html.erb
<div>
  <h2 style="margin-left: 30px; font-family: Helvetica, sans-serif">Nos Valeurs</h2>
  <div class="valeurs-cards">
    <div class="card card1-apprentis-comp">
      <header>
        <%= image_tag "logos/brain-line-icon.png", width: "15%"%>
        <h2>Apprentissage des compétences </h2>
      </header><br/>
      <p> Le cbg School offre aux élève un enseignement 
        de qualité dès les bas ages et au standard international pour les outiller afin d’affronter les défis et les opportunités 
        dans leur parcours académique et de leur future vie professionnelle"
      </p>
    </div>
    <div class="card card2-enseign-qualif">
      <header>
        <%= image_tag "logos/training-icon.png", width: "15%"%>
        <h2>Enseignants qualifiés</h2> <br/>
      </header>
      <p>
        Le staff professoral de notre école est constitué des meilleurs enseignants 
        qualifiés pour l'enseinement de l'école maternel, primaire et secondaire pour le programme 
        national congolais et le curriculum britannique. 
        Nous offrons l'enseignement des enfants avec l'habilité limitée, pour leurs besoins spécifiques 
        avec l'appuis de nos partenaire nationaux et internationaux."
      </p>
    </div>
    <div class="card card3-accreditation">
      <header>
        <%= image_tag "logos/Diploma.png", width: "15%"%>
        <h2>Accreditation</h2><br/>
      </header>
      <p>
          Notre aspiration est d'avoir l'accréditation auprès 
          du Conseil Britannique pour l'Education En RD Cong."
      </p>
    </div>
  </div>
</div>
<div class="philosophy">
  <%= image_tag('logos/philosophievaleurs.svg', alt: 'philosophie', class: 'philosophie') %>
</div>

<div class="apropos" id="apropos">
  <%= image_tag('logos/apropossection.svg', alt: 'philosophie', class: 'philosophie') %>
</div>

app/views/home/_uppernav.html.erb
<div>
  <ul class='uppernav'>
    <li class="uppernav-link uppernave-icon"> <a href="tel:0974469299"><i class="bi bi-telephone-forward-fill"></i> <div class="icon-name"> Tél: +243 974 469 299</div></li>
    <li class="uppernav-link uppernave-icon"> <a href = "mailto: direction2cbgschool-cd.org"> <i class="bi bi-envelope-fill"></i> <div class="icon-name"> email </div> </a> </li>
    <li class="uppernav-link uppernave-icon"> <a href = "https://youtube.com/@CBG_School?si=F7Jg_wac383b87op"><i class="bi bi-youtube"></i><div class="icon-name">Youtube</div></a> </li>
    <li class="uppernav-link uppernave-icon"> <a href = "https://www.tiktok.com/@cbgschool243?is_from_webapp=1&sender_device=pc"> <i class="bi bi-tiktok"></i> <div class="icon-name">tiktok </div> </a></li>
    <li class="uppernav-link uppernave-icon"> <a href = "https://www.instagram.com/cbg_school/"> <i class="bi bi-instagram"></i><div class="icon-name"> instagram </div> </a> </li>
  </ul>
</div>
<div class="navbar navbar-expand-lg d-flex">
  <div class="logo">
    <%= image_tag"logos/CBGClogo.png", class: 'my-logo'%>
  </div>
  <%= render 'shared/dropdown'%>
</div>

app/views/home/index.html.erb
<%= render "uppernav" %>
<div>
<%################### BOOTSTRAP SLIDER ###############%>
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <%= image_tag "logos/cbg1.jpeg", class: "d-block w-100" %>
        </div>
        <div class="carousel-item">
          <%= image_tag "logos/cbg3.jpeg", class: "d-block w-100"%>
        </div>
        <div class="carousel-item">
          <%= image_tag "logos/cbg2.jpeg", class: "d-block w-100" %>
        </div>
        <div class="carousel-item">
          <%= image_tag "logos/cbg4.jpeg", class: "d-block w-100" %>
        </div>
        <div class="carousel-item">
          <%= image_tag "logos/cbg5.jpeg", class: "d-block w-100" %>
        </div>
        <div class="carousel-item">
          <%= image_tag "logos/cbg6.jpeg", class: "d-block w-100" %>
        </div>
        <div class="carousel-item">
          <%= image_tag "logos/cbg7.jpeg", class: "d-block w-100" %>
        </div>
        <div class="carousel-item">
          <%= image_tag "logos/eleveimg9.jpeg", class: "d-block w-100" %>
        </div>
        <div class="carousel-item">
          <%= image_tag "logos/eleveimg10.jpeg", class: "d-block w-100" %>
        </div>
        <div class="carousel-item">
          <%= image_tag "logos/eleveimg11.jpeg", class: "d-block w-100" %>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
  </div>
  <%################### BOOTSTRAP SLIDER ###############%>
    <div style="white-space: nowrap; overflow: hidden; width: 100%; background-color: #c0c4c7; padding: 20px">
      <span class="sliding-text" style="display: inline-block; animation: slidein 20s linear infinite; font-size: 30px; font-weight: bold; font-family: Helvetica, sans-serif; color: #fff">
        NOTRE DEVISE : EXCELLENCE DISCIPLINE ET QUALITE
      </span>
    </div>
    <div class="section-equipe-dirigeante">
      <h2 class="equipe-dir">Equipe dirigeante</h2>
      <div class="equipe-dir-pics">
        <div style="text-align: center">
          <%= image_tag "logos/prompic 1.png", width: "65%", margin: "auto" %>
          <div style="text-align: center"><h3>Promotrice  <br/> Madame Sylvie Kafat </h3> </div>
        </div>
      </div>
    </div>
    <div class="section-nos-valeurs">
      <%= render "nosvaleurs"%>
    </div>
    <div class="section-organisees-container">
    <h2 style="font-family: Helvetica, sans-serif">Section organisées</h2>
    <div class="section-organisees">
      <div class="section-card section-maternelle">
         <h3>SECTION MATERNELLE</h3>
         
         <button class="popup-btn">Detail sur la section</button>
         <%= render 'shared/popup' do %>
            <p>
               <h3>Section Maternelle</h3><br/>
               CBG-SCHOOL offre aux enfants de la maternelle la formation et l'encadrement 
               visant la production d'expression orale du Français et de l'Anglais, les notions 
               essentielles de la numérique, d'hygiène, de l'environnement et des relations humaines. 
               Les classes ont 
               les niveaux 1,2 et 3 dont la capacité est prévue de 20 à 30 élèves (3 salles).
           </p>
         <% end %>
      </div>
      <div class="section-card section-primaire">
         <h3>SECTION PRIMAIRE</h3>
         <button class="popup-btn">Detail sur la section</button>
         <%= render 'shared/popup' do %>
            <p>
              <h3>SECTION PRIMAIRE</h3> <br/>
              Notre école est résolue à donner aux enfants une formation intégrale d'excellence 
              en lecture, écriture, arithmétique. La formation vise la bonne compréhension de la 
              matière dispensée, l'aisance dans l'expression en langue française et anglaise. 
              Les classes de la 1ère ,2ième, 3ième ,4 ème , 5ième et 6ième avec classe parallèle 1A 
              et 1B dont la capacité d'accueil est 30 à 35 élèves (12 Salles).
            </p>
         <% end %>
      </div>
      <div class="section-card section-secondaire">
         <h3>SECTION SECONDAIRE </h3>
         
         <button class="popup-btn">Detail sur la section</button>
         <%= render 'shared/popup' do %>
            <p>
              <h3>SECTION SECONDAIRE</h3><br/>
              Notre école s'assure qu'a l'issue de l'enseignement secondaire l'élève acquière 
              la connaissance générale et spécifique du monde quI L'entoure. La formation d'être un bon 
              citoyen responsable pour contribuer au développement 
              de sa communauté et du pays. Elle veille à la formation à la citoyenneté 
              responsable afin de contribuer au développement de la communauté et du pays. 
              Les classes de la 7ième et 8 ième ont la capacité de 30-35 élèves 
              avec classe parallèle A &B (4 salles). 
              Les classes supérieures du secondaire sont en progression. (4 Salles)
           </p>
          <% end %>
      </div>
    </div>
    </div>

    <div class="promot-speech">
      <h2 style="font-family: Helvetica, sans-serif">Mot de La Promotrice </h2> <br/>
      <%= image_tag("logos/mamansylvy.svg", width: "60%", margin: '0 auto')%>
    </div>
    <h2 style="text-align: center; font-family: Helvetica, sans-serif">Nos formations</h2> <br/>
    <div class="youtube-container">
      <div class="formations">
        <div class="compte">
          <%= image_tag "logos/accountancy.png", class: "formapic"%>
        </div>
        <h4>Comptabilité</h4>
      </div>
      <div class="informatique">
        <div class="compte">
          <%= image_tag "logos/itformation.png", class: "infopic"%>
        </div>
        <h4>Informatique de gestion</h4>
      </div>
    </div>
    <div class="nos-partenaires">
      <h2 style="font-family: Helvetica, sans-serif">Nos Partneraires</h2>
      <div class="partenaire-container" >
        <div class = "partner-pic-container"><%= image_tag "logos/lualabaflagpic.png", class: "partnerpic"%></div>
        <div class = partner-pic-container><%= image_tag "logos/british-grammar-school.png", class: "bgs-icon"%></div>
      </div>
    </div>
    <div class="footer">
      <%= render "footer"%>
    </div>
</div>