config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms
  get 'dashboard/index', to: 'dashboard#index'
  get 'dashboard/new', to: 'dashboard#new'
  get 'dashboard/create', to: 'dashboard#create'
  get 'dashboard/edit', to: 'dashboard#edit'
  get 'dashboard/update', to: 'dashboard#index'
  get 'dashboard/destroy', to: 'dashboard#destroy'
  get 'dashboard/chats', to: 'dashboard#chats'

  
  namespace :admin do
    resources :links, only: [:new, :create, :index, :show]
    resources :events, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :messages, only: [:index, :show, :destroy]
    resources :chats, only: [:index, :show, :new, :create]
    resources :chatrooms, only: [:index, :show, :new, :update, :edit, :destroy]
    resources :teachers do
      collection do
        get '/search', to: 'teachers#search'
      end
    end
    resources :parents, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      collection do
        get '/search', to: 'parents#search'
      end
    end
    resources :home do
      collection do
        get '/logged_in_users', to: 'home#logged_in_users', as: 'logged_in_users'
      end
    end
    resources :communiques, only: [:index, :show, :destroy, :new, :create, :edit, :update]
    resources :eleves, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :letters, only: [:index, :create, :new, :show]

    get '/search', to: 'eleves#search'
    resources :chatrooms do
      resource :chatroom_users
      resources :instant_messages
    end
    
  end 
  
  resources :eleves, only: [:index, :show]
  resources :teachers, only: [:index, :show]
  resources :communiques, only: [:index, :show]
  resources :home, only: [:index]
  resources :messages, only: [:show, :update, :destroy, :new, :create, :edit]
  resources :chats, only: [:index]
  resources :events, only: [:index]
  resources :links, only: [:index, :show]


  
  # resources :dashboard, only: [:index, :update, :create, :new, :edit, :destroy]
  
  # get 'home/dashboard', to: 'dashboard#index'

 
  # devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "home#index"
  resources :chatrooms do
    resource :chatroom_users
    resources :instant_messages
  end

end

app/models/UserChat.rb
class UserChat < ApplicationRecord
  belongs_to :user
  belongs_to :chat
end

app/models/chat.rb
class Chat < ApplicationRecord
 
  belongs_to :sender, class_name: "User"
  has_many :user_chats
  has_many :recipients, through: :user_chats, source: :user, class_name: "User"
  has_many :received_chats, class_name: "Chat", foreign_key: "sender"

end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
    has_many :chatroom_users
    has_many :users, through: :chatroom_users
    has_many :instant_messages
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/communique.rb
class Communique < ApplicationRecord
    has_one_attached :image
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/eleve.rb
class Eleve < ApplicationRecord
    # after_create_commit { broadcast_prepend_to "tweets" }
end

app/models/event.rb
class Event < ApplicationRecord
    has_one_attached :image
    has_one_attached :document
end

app/models/instant_message.rb
class InstantMessage < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/letter.rb
class Letter < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"

  has_many :received_letters, class_name: "Letter", foreign_key: "recipient_id"
  has_many :sent_letters, class_name: "Letter", foreign_key: "sender_id"

  has_one_attached :document

end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/parent.rb
class Parent < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :sent_letters, class_name: "Letter", foreign_key: "sender_id"
  has_many :received_letters, class_name: "Letter", foreign_key: "recipient_id"
  has_many :user_chats
  has_many :chats, through: :user_chats, source: :chats
  has_many :received_chats, class_name: "Chat", foreign_key: "sender"
  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :intant_messages

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true, length: { minimum: 6 }


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  def self.first_user?
    count == 1
  end


  after_create :set_first_user_as_admin

  private

  def set_first_user_as_admin
    if User.first_user?
      update(is_admin: true)
    end
  end
end

app/controllers/admin/communiques_controller.rb
class Admin::CommuniquesController < ApplicationController
  before_action :set_communique, only: %i[show edit update destroy ]
  before_action :authenticate_user!
  before_action :check_if_admin

  def index 
    @communiques = Communique.all
  end

  # GET /communiques/1 or /communiques/1.json
  def show
    @communique = Communique.find(params[:id])
  end

  # GET /communiques/new
  def new
    @communique = Communique.new
  end

  # GET /communiques/1/edit
  def edit
  end

  # POST /communiques or /communiques.json
  def create
    @communique = Communique.new(communique_params)

    respond_to do |format|
      if @communique.save
        format.html { redirect_to communique_url(@communique), notice: "Communique ajoute avec success" }
        format.json { render :show, status: :created, location: @communique }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @communique.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communiques/1 or /communiques/1.json
  def update
    respond_to do |format|
      if @communique.update(communique_params)
        format.html { redirect_to communique_url(@communique), notice: "Communique was successfully updated." }
        format.json { render :show, status: :ok, location: @communique }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @communique.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communiques/1 or /communiques/1.json
  def destroy
    @communique.destroy

    respond_to do |format|
      format.html { redirect_to admin_communiques_path, notice: "Communique efface avec succes." }
      format.json { head :no_content }
    end
  end

  private

    def check_if_admin
      redirect_to root_path unless current_user.is_admin?
    end

    def set_communique
      @communique = Communique.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def communique_params
      params.require(:communique).permit(:titre, :description, :image)
    end

end

app/controllers/communiques_controller.rb
class CommuniquesController < ApplicationController

  # GET /communiques or /communiques.json
  def index
    @communiques = Communique.all
  end

  # GET /communiques/1 or /communiques/1.json
  def show
    @communique = Communique.find(params[:id])
  end
end

app/helpers/communiques_helper.rb
module CommuniquesHelper
end

app/helpers/eleves_helper.rb
module ElevesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/admin/communiques/_communique.html.erb
<p style="color: green"><%= notice %></p>

<%= render @communique %>

<div>
  <%= link_to "Modifier", edit_admin_communique_path(@communique) %> 
  <%= link_to "Retourner aux communiquer", admin_communiques_path %>

  <%= button_to "Effacer le communique", @communique, method: :delete %>
</div>

app/views/admin/communiques/_form.html.erb
<div class="signup">
  <%= form_with(model: [:admin, Communique.new], local: true) do |form| %>
    <% if @communique.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@communique.errors.count, "error") %> prohibited this communique from being saved:</h2>
        <ul>
        <% @communique.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= form.label :titre, class: 'label' %>
      <%= form.text_field :titre, class: 'input' %>
    </div>
    <div>
      <%= form.label :description, class: 'label' %>
      <%= form.text_field :description, class: 'input' %>
    </div>
    <div>
      <%= form.label :image, class: 'label' %>
      <%= form.file_field :image, class: 'input' %>
    </div>
    <div>
      <%= form.submit class: "button" %>
    </div>
  <% end %>
</div>

app/views/admin/communiques/edit.html.erb
<h1>Editing communique</h1>

<%= render "form", communique: @communique %>

<br>

<div>
  <%= link_to "Show this communique", @communique %> |
  <%= link_to "Back to communiques", admin_communiques_path %>
</div>

app/views/admin/communiques/index.html.erb
<div class="news-page">
  <h1>Communiques recents</h1>
  <%= link_to "+ Ajouter", new_admin_communique_path, class: "btn-new-teacher" %>
  <hr>
  
  <% @communiques.each do |communique| %>
    <div class="article">
      <h2><%= communique.titre %></h2>
      <p class="date">Date d'ajout: <%= communique.created_at.strftime("%B %d, %Y") %></p>
      <% if communique.image.attached? %>
        <%= image_tag communique.image, style: "width: 80%; height: 100%; margin: 10px auto; object-fit: fit" %>
      <% else %>
      <p class="summary"><%= communique.description %></p><br/>
        <div>Pas d'image</div>
      <% end %>
      <p class="read-more">
        <%= link_to "Voir", communique %>
        <%= button_to "Effacer", admin_communique_path(communique), method: :delete, data: { confirm: "Êtes-vous sûr?" }, class: "button", style: "width: 30%, margin: auto"%>
      </p>
    </div>
    <hr>
  <% end %>
  
  <%= link_to "Voir tous les communiques crees", admin_communiques_path, class: "btn" %>
  
</div>

app/views/admin/communiques/new.html.erb
<div style="text-align: center; margin-top: 3rem;">
<h1>New communique</h1>

<%= render "form", communique: @communique %>

<br>

<div>
  <%= link_to "Back to communiques", admin_communiques_path %>
</div>
</div>

app/views/admin/communiques/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @communique %>

<div>
  <%= link_to "Modifier", edit_admin_communique_path(@communique) %> |
  <%= link_to "Retourner aux communiques", admin_communiques_path %>

  <%= button_to "Effacer le communique", @communique, method: :delete %>
</div>

app/views/communiques/index.html.erb
<div style="display:flex; justify-content:center;">
  
  <p style="color: green"><%= notice %></p>
 
<div id="communiques" style="margin-top: 3rem; text-align:center ">
   <%= link_to(root_path) do%> <%= image_tag"logos/CBGClogo.png", class: 'my-logo-popup-icon' %> <% end %>

  
  <h1>Communiques</h1> <br />

  <% @communiques.each do |communique| %>
   <div style="border-radius: 20px; border-bottom: 1px solid black; padding: 15px">
    <h3><%= communique.titre%></h3> <br/>
    <% if communique.image.attached? %>
      <%= image_tag communique.image, style: "width: 60%; height: 245px; margin: 10px auto; object-fit: contain" %>
    <% else %>
      <div>Pas d'image rattachée</div>
    <% end %>
    <p><%= communique.description%></p> <br/>
    <p style="padding: 7px; border-radius: 8px; width: max-content; margin-bottom: 7px; background-color: black ">
      <%= link_to "voir", communique, style: "text-decoration: none; color: white" %>
    </p>
   </div> 
  <% end %>
</div>


</div>

app/views/communiques/show.html.erb
<p style="color: green"><%= notice %></p>
<div style="text-align: center; margin-top: 4rem">
   <%= image_tag"logos/CBGClogo.png", class: 'my-logo-popup-icon' %> <br/>
   <p>
     <h1><%= @communique.titre %></h1> <br/>
   </p>
   <% if @communique.image.attached? %>
      <%= image_tag @communique.image, style: "width: 60%; height: 245px; margin: 10px auto; object-fit: contain" %>
   <% else %> 
      <div style="color: red">Pas d'image trouvée</div>
   <% end %>  

   <p style="width: 65%; margin: auto"><%= @communique.description %></p>
   <div style="margin: 25px;">
     <div style="margin: 15px;"><%= link_to "Retour aux communiques", communiques_path, style: "text-decoration: none; background-color: black; color: white; padding: 7px; border-radius: 7px; " %></div>
     <% if current_user.is_admin?%>
       <div style="margin: 15px;"><%= link_to "Retour aux communiques administrateur", admin_communiques_path, style: "text-decoration: none; background-color: black; color: white; padding: 7px; border-radius: 7px; " %><div style="margin: 15px;">
     <% end %> 
   </div>
</div>